### ISSUE TITLE
todo: refac

### ISSUE THREAD

**Issue by bobanko** [ElenaOzhoga/game#4]
- [ ] разрезать код на отдельные функции / структурировать код
- [ ] избавиться от дублирования
- [ ] сделать код масштабируемым (чтобы можно было легко поменять размеры поля например)
- [ ] пофиксить баги
